import { jsPDF } from "jspdf";
import { QuizQuestion } from "../types";

export function exportQuizAsPDF(
  questions: QuizQuestion[],
  category: string,
  difficulty: string,
  score: number
) {
  const doc = new jsPDF();

  // Draw header accent
  doc.setFillColor(37, 99, 235); // Blue primary
  doc.rect(0, 0, 210, 40, "F");

  // Title inside the blue accent
  doc.setTextColor(255, 255, 255);
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(22);
  doc.text("WGTBAM 2.0 Prep AI Report", 15, 25);

  doc.setFontSize(10);
  doc.setFont("Helvetica", "normal");
  doc.text("Official Contestant Preparation Platform", 15, 33);

  // Meta metadata panel
  doc.setFillColor(243, 244, 246);
  doc.rect(15, 48, 180, 26, "F");

  doc.setTextColor(55, 65, 81);
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Category: ${category}`, 20, 56);
  doc.text(`Difficulty: ${difficulty}`, 20, 62);
  doc.text(`Questions: ${questions.length}`, 110, 56);
  doc.text(`Prepped Score: ${score} / ${questions.length}`, 110, 62);

  // Divider
  doc.setDrawColor(209, 213, 219);
  doc.line(15, 80, 195, 80);

  // Print quiz items
  doc.setFont("Helvetica", "normal");
  let currentY = 90;

  questions.forEach((q, idx) => {
    // Check page overflow
    if (currentY > 260) {
      doc.addPage();
      currentY = 25; // Header space of next page
    }

    doc.setTextColor(17, 24, 39);
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(11);
    
    // Auto-wrap question text
    const questionLines = doc.splitTextToSize(`${idx + 1}. ${q.question}`, 175);
    doc.text(questionLines, 15, currentY);
    currentY += questionLines.length * 6;

    // Options layout
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99);

    const options = [
      `A. ${q.optionA}`,
      `B. ${q.optionB}`,
      `C. ${q.optionC}`,
      `D. ${q.optionD}`,
    ];

    options.forEach((opt) => {
      if (currentY > 275) {
        doc.addPage();
        currentY = 25;
      }
      doc.text(opt, 22, currentY);
      currentY += 5.5;
    });

    // Display correct answer key
    if (currentY > 275) {
      doc.addPage();
      currentY = 25;
    }
    doc.setFont("Helvetica", "bold");
    doc.setTextColor(16, 185, 129); // green success
    doc.text(`Correct: [Option ${q.correctAnswer}]`, 22, currentY);
    
    doc.setFont("Helvetica", "normal");
    currentY += 10; // Margin after block
  });

  // Footer text
  if (currentY > 270) {
    doc.addPage();
    currentY = 25;
  }
  doc.setDrawColor(229, 231, 235);
  doc.line(15, currentY, 195, currentY);
  currentY += 8;
  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by WGTBAM 2.0 Prep AI. All rights reserved.", 15, currentY);

  // Save PDF
  doc.save(`wgtbam_prep_${category.replace(/\s+/g, "_").toLowerCase()}_report.pdf`);
}
